version: "3"

services:
  sonarqube:
    image: sonarqube:9.1.0-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=123456
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
